# Generated by Django 4.2.19 on 2025-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
