# Generated by Django 4.2.19 on 2025-02-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(
                error_messages={"blank": "Le titre est obligatoire."}, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                error_messages={"blank": "Le titre est obligatoire."}, max_length=128
            ),
        ),
    ]
